package com.direwolf20.justdirethings.datagen;

import com.direwolf20.justdirethings.JustDireThings;
import com.direwolf20.justdirethings.common.items.interfaces.Ability;
import com.direwolf20.justdirethings.setup.JDTRegistration;
import com.direwolf20.justdirethings.setup.ModSetup;
import net.minecraft.data.PackOutput;


public class JustDireLanguageProvider extends net.neoforged.neoforge.common.data.LanguageProvider {
    public JustDireLanguageProvider(PackOutput output, String locale) {
        super(output, JustDireThings.MODID, locale);
    }

    @Override
    protected void addTranslations() {
        add("itemGroup." + ModSetup.TAB_JUSTDIRETHINGS, "Just Dire Things");

        //Blocks
        add(JDTRegistration.GooSoil_Tier1.get(), "Primogel Soil");
        add(JDTRegistration.GooSoil_Tier2.get(), "Blazebloom Soil");
        add(JDTRegistration.GooSoil_Tier3.get(), "VoidShimmer Soil");
        add(JDTRegistration.GooSoil_Tier4.get(), "Shadowpulse Soil");
        add(JDTRegistration.GooBlock_Tier1.get(), "Primogel Goo");
        add(JDTRegistration.GooBlock_Tier1.get() + "_dead", "Exhausted Primogel Goo");
        add(JDTRegistration.GooBlock_Tier2.get(), "Blazebloom Goo");
        add(JDTRegistration.GooBlock_Tier2.get() + "_dead", "Exhausted Blazebloom Goo");
        add(JDTRegistration.GooBlock_Tier3.get(), "VoidShimmer Goo");
        add(JDTRegistration.GooBlock_Tier3.get() + "_dead", "Exhausted VoidShimmer Goo");
        add(JDTRegistration.GooBlock_Tier4.get(), "Shadowpulse Goo");
        add(JDTRegistration.GooBlock_Tier4.get() + "_dead", "Exhausted Shadowpulse Goo");
        add(JDTRegistration.ItemCollector.get(), "Item Collector");
        add(JDTRegistration.BlockBreakerT1.get(), "Simple Block Breaker");
        add(JDTRegistration.BlockBreakerT2.get(), "Advanced Block Breaker");
        add(JDTRegistration.BlockPlacerT1.get(), "Simple Block Placer");
        add(JDTRegistration.BlockPlacerT2.get(), "Advanced Block Placer");
        add(JDTRegistration.ClickerT1.get(), "Simple Clicker");
        add(JDTRegistration.ClickerT2.get(), "Advanced Clicker");
        add(JDTRegistration.SensorT1.get(), "Simple Sensor");
        add(JDTRegistration.SensorT2.get(), "Advanced Sensor");
        add(JDTRegistration.DropperT1.get(), "Simple Dropper");
        add(JDTRegistration.DropperT2.get(), "Advanced Dropper");
        add(JDTRegistration.GeneratorT1.get(), "Simple Coal Generator");
        add(JDTRegistration.GeneratorFluidT1.get(), "Simple Fuel Generator");
        add(JDTRegistration.EnergyTransmitter.get(), "Energy Transmitter");
        add(JDTRegistration.BlockSwapperT1.get(), "Simple Swapper");
        add(JDTRegistration.BlockSwapperT2.get(), "Advanced Swapper");
        add(JDTRegistration.PlayerAccessor.get(), "Player Accessor");
        add(JDTRegistration.EclipseGateBlock.get(), "Eclipse Gate");
        add(JDTRegistration.FluidPlacerT1.get(), "Simple Fluid Placer");
        add(JDTRegistration.FluidPlacerT2.get(), "Advanced Fluid Placer");
        add(JDTRegistration.FluidCollectorT1.get(), "Simple Fluid Collector");
        add(JDTRegistration.FluidCollectorT2.get(), "Advanced Fluid Collector");
        add(JDTRegistration.TimeCrystalBlock.get(), "Time Crystal Block");
        add(JDTRegistration.TimeCrystalBuddingBlock.get(), "Budding Time Crystal Block");
        add(JDTRegistration.TimeCrystalCluster.get(), "Time Crystal Cluster");
        add(JDTRegistration.TimeCrystalCluster_Small.get(), "Small Time Crystal Cluster");
        add(JDTRegistration.TimeCrystalCluster_Medium.get(), "Medium Time Crystal Cluster");
        add(JDTRegistration.TimeCrystalCluster_Large.get(), "Large Time Crystal Cluster");
        add(JDTRegistration.ParadoxMachine.get(), "Paradox Machine");
        add(JDTRegistration.InventoryHolder.get(), "Inventory Holder");
        add(JDTRegistration.ExperienceHolder.get(), "Experience Holder");

        //Fluids
        add(JDTRegistration.PORTAL_FLUID_BLOCK.get(), "Portal Fluid");
        add(JDTRegistration.PORTAL_FLUID_BUCKET.get(), "Portal Fluid Bucket");
        add("fluid_type.justdirethings.portal_fluid_type", "Portal Fluid");
        add(JDTRegistration.UNSTABLE_PORTAL_FLUID_BLOCK.get(), "Unstable Portal Fluid");
        add(JDTRegistration.UNSTABLE_PORTAL_FLUID_BUCKET.get(), "Unstable Portal Fluid Bucket");
        add("fluid_type.justdirethings.unstable_portal_fluid_type", "Unstable Portal Fluid");
        add(JDTRegistration.POLYMORPHIC_FLUID_BLOCK.get(), "Polymorphic Fluid");
        add(JDTRegistration.POLYMORPHIC_FLUID_BUCKET.get(), "Polymorphic Fluid Bucket");
        add("fluid_type.justdirethings.polymorphic_fluid_type", "Polymorphic Fluid");
        add(JDTRegistration.UNREFINED_T2_FLUID_BLOCK.get(), "Unrefined Blaze Ember Fuel");
        add(JDTRegistration.UNREFINED_T2_FLUID_BUCKET.get(), "Unrefined Blaze Ember Fuel Bucket");
        add("fluid_type.justdirethings.unrefined_t2_fluid_type", "Unrefined Blaze Ember Fuel");
        add(JDTRegistration.REFINED_T2_FLUID_BLOCK.get(), "Blaze Ember Fuel");
        add(JDTRegistration.REFINED_T2_FLUID_BUCKET.get(), "Blaze Ember Fuel Bucket");
        add("fluid_type.justdirethings.refined_t2_fluid_type", "Blaze Ember Fuel");
        add(JDTRegistration.UNREFINED_T3_FLUID_BLOCK.get(), "Unrefined Voidflame Fuel");
        add(JDTRegistration.UNREFINED_T3_FLUID_BUCKET.get(), "Unrefined Voidflame Fuel Bucket");
        add("fluid_type.justdirethings.unrefined_t3_fluid_type", "Unrefined Voidflame Fuel");
        add(JDTRegistration.REFINED_T3_FLUID_BLOCK.get(), "Voidflame Fuel");
        add(JDTRegistration.REFINED_T3_FLUID_BUCKET.get(), "Voidflame Fuel Bucket");
        add("fluid_type.justdirethings.refined_t3_fluid_type", "Voidflame Fuel");
        add(JDTRegistration.UNREFINED_T4_FLUID_BLOCK.get(), "Unrefined Eclipse Ember Fuel");
        add(JDTRegistration.UNREFINED_T4_FLUID_BUCKET.get(), "Unrefined Eclipse Ember Fuel Bucket");
        add("fluid_type.justdirethings.unrefined_t4_fluid_type", "Unrefined Eclipse Ember Fuel");
        add(JDTRegistration.REFINED_T4_FLUID_BLOCK.get(), "Eclipse Ember Fuel");
        add(JDTRegistration.REFINED_T4_FLUID_BUCKET.get(), "Eclipse Ember Fuel Bucket");
        add("fluid_type.justdirethings.refined_t4_fluid_type", "Eclipse Ember Fuel");
        add(JDTRegistration.TIME_FLUID_BLOCK.get(), "Time Fluid");
        add(JDTRegistration.TIME_FLUID_BUCKET.get(), "Time Fluid Bucket");
        add("fluid_type.justdirethings.time_fluid_type", "Time Fluid");
        add(JDTRegistration.XP_FLUID_BLOCK.get(), "XP Fluid");
        add(JDTRegistration.XP_FLUID_BUCKET.get(), "XP Fluid Bucket");
        add("fluid_type.justdirethings.xp_fluid_type", "XP Fluid");

        //Resources
        add(JDTRegistration.FerricoreBlock.get(), "Ferricore Block");
        add(JDTRegistration.RawFerricoreOre.get(), "Raw Ferricore Ore");
        add(JDTRegistration.BlazeGoldBlock.get(), "Blazegold Block");
        add(JDTRegistration.RawBlazegoldOre.get(), "Raw Blazegold Ore");
        add(JDTRegistration.RawCelestigemOre.get(), "Raw Celestigem Ore");
        add(JDTRegistration.CelestigemBlock.get(), "Celestigem Block");
        add(JDTRegistration.RawEclipseAlloyOre.get(), "Raw Eclipse Alloy Ore");
        add(JDTRegistration.EclipseAlloyBlock.get(), "Eclipse Alloy Block");
        add(JDTRegistration.CharcoalBlock.get(), "Charcoal Block");
        add(JDTRegistration.RawCoal_T1.get(), "Raw Primal Coal");
        add(JDTRegistration.CoalBlock_T1.get(), "Primal Coal Block");
        add(JDTRegistration.RawCoal_T2.get(), "Raw Blaze Ember");
        add(JDTRegistration.CoalBlock_T2.get(), "Blaze Ember Block");
        add(JDTRegistration.RawCoal_T3.get(), "Raw Voidflame Coal");
        add(JDTRegistration.CoalBlock_T3.get(), "Voidflame Coal Block");
        add(JDTRegistration.RawCoal_T4.get(), "Raw Eclipse Ember");
        add(JDTRegistration.CoalBlock_T4.get(), "Eclipse Ember Block");
        add(JDTRegistration.PolymorphicCatalyst.get(), "Polymorphic Catalyst");
        add(JDTRegistration.PortalFluidCatalyst.get(), "Portal Fluid Catalyst");
        add(JDTRegistration.TimeCrystal.get(), "Time Crystal");

        //Items
        add(JDTRegistration.Fuel_Canister.get(), "Fuel Canister");
        add(JDTRegistration.Pocket_Generator.get(), "Pocket Generator");
        add(JDTRegistration.TotemOfDeathRecall.get(), "Totem of Death Recall");
        add(JDTRegistration.BlazejetWand.get(), "Blazejet Wand");
        add(JDTRegistration.VoidshiftWand.get(), "Voidshift Wand");
        add(JDTRegistration.EclipsegateWand.get(), "Eclipsegate Wand");
        add(JDTRegistration.CreatureCatcher.get(), "Creature Catcher");
        add(JDTRegistration.MachineSettingsCopier.get(), "Machine Settings Copier");
        add(JDTRegistration.PortalGun.get(), "Portal Gun");
        add(JDTRegistration.PortalGunV2.get(), "Advanced Portal Gun");
        add(JDTRegistration.FluidCanister.get(), "Fluid Canister");
        add(JDTRegistration.PotionCanister.get(), "Potion Canister");
        add(JDTRegistration.TimeWand.get(), "Time Wand");
        add(JDTRegistration.PolymorphicWand.get(), "Polymorphic Wand");
        add(JDTRegistration.PolymorphicWandV2.get(), "Advanced Polymorphic Wand");

        //Tools
        add(JDTRegistration.FerricoreSword.get(), "Ferricore Sword");
        add(JDTRegistration.FerricorePickaxe.get(), "Ferricore Pickaxe");
        add(JDTRegistration.FerricoreShovel.get(), "Ferricore Shovel");
        add(JDTRegistration.FerricoreAxe.get(), "Ferricore Axe");
        add(JDTRegistration.FerricoreHoe.get(), "Ferricore Hoe");
        add(JDTRegistration.BlazegoldSword.get(), "Blazegold Sword");
        add(JDTRegistration.BlazegoldPickaxe.get(), "Blazegold Pickaxe");
        add(JDTRegistration.BlazegoldShovel.get(), "Blazegold Shovel");
        add(JDTRegistration.BlazegoldAxe.get(), "Blazegold Axe");
        add(JDTRegistration.BlazegoldHoe.get(), "Blazegold Hoe");
        add(JDTRegistration.CelestigemSword.get(), "Celestigem Sword");
        add(JDTRegistration.CelestigemPickaxe.get(), "Celestigem Pickaxe");
        add(JDTRegistration.CelestigemShovel.get(), "Celestigem Shovel");
        add(JDTRegistration.CelestigemAxe.get(), "Celestigem Axe");
        add(JDTRegistration.CelestigemHoe.get(), "Celestigem Hoe");
        add(JDTRegistration.EclipseAlloySword.get(), "Eclipse Alloy Sword");
        add(JDTRegistration.EclipseAlloyPickaxe.get(), "Eclipse Alloy Pickaxe");
        add(JDTRegistration.EclipseAlloyShovel.get(), "Eclipse Alloy Shovel");
        add(JDTRegistration.EclipseAlloyAxe.get(), "Eclipse Alloy Axe");
        add(JDTRegistration.EclipseAlloyHoe.get(), "Eclipse Alloy Hoe");
        add(JDTRegistration.CelestigemPaxel.get(), "Celestigem Paxel");
        add(JDTRegistration.EclipseAlloyPaxel.get(), "Eclipse Alloy Paxel");
        add(JDTRegistration.FerricoreWrench.get(), "Ferricore Wrench");
        add(JDTRegistration.FerricoreBow.get(), "Ferricore Bow");
        add(JDTRegistration.BlazegoldBow.get(), "Blazegold Bow");
        add(JDTRegistration.CelestigemBow.get(), "Celestigem Bow");
        add(JDTRegistration.EclipseAlloyBow.get(), "Eclipse Alloy Bow");

        //Armors
        add(JDTRegistration.FerricoreBoots.get(), "Ferricore Boots");
        add(JDTRegistration.FerricoreChestplate.get(), "Ferricore Chestplate");
        add(JDTRegistration.FerricoreLeggings.get(), "Ferricore Leggings");
        add(JDTRegistration.FerricoreHelmet.get(), "Ferricore Helmet");
        add(JDTRegistration.BlazegoldBoots.get(), "Blazegold Boots");
        add(JDTRegistration.BlazegoldChestplate.get(), "Blazegold Chestplate");
        add(JDTRegistration.BlazegoldLeggings.get(), "Blazegold Leggings");
        add(JDTRegistration.BlazegoldHelmet.get(), "Blazegold Helmet");
        add(JDTRegistration.CelestigemBoots.get(), "Celestigem Boots");
        add(JDTRegistration.CelestigemChestplate.get(), "Celestigem Chestplate");
        add(JDTRegistration.CelestigemLeggings.get(), "Celestigem Leggings");
        add(JDTRegistration.CelestigemHelmet.get(), "Celestigem Helmet");
        add(JDTRegistration.EclipseAlloyBoots.get(), "Eclipse Alloy Boots");
        add(JDTRegistration.EclipseAlloyChestplate.get(), "Eclipse Alloy Chestplate");
        add(JDTRegistration.EclipseAlloyLeggings.get(), "Eclipse Alloy Leggings");
        add(JDTRegistration.EclipseAlloyHelmet.get(), "Eclipse Alloy Helmet");

        //Resources
        add(JDTRegistration.FerricoreIngot.get(), "Ferricore Ingot");
        add(JDTRegistration.RawFerricore.get(), "Raw Ferricore");
        add(JDTRegistration.BlazegoldIngot.get(), "Blazegold Ingot");
        add(JDTRegistration.RawBlazegold.get(), "Raw Blazegold");
        add(JDTRegistration.Celestigem.get(), "Celestigem");
        add(JDTRegistration.EclipseAlloyIngot.get(), "Eclipse Alloy Ingot");
        add(JDTRegistration.RawEclipseAlloy.get(), "Raw Eclipse Alloy");
        add(JDTRegistration.Coal_T1.get(), "Primal Coal");
        add(JDTRegistration.Coal_T2.get(), "Blaze Ember");
        add(JDTRegistration.Coal_T3.get(), "Voidflame Coal");
        add(JDTRegistration.Coal_T4.get(), "Eclipse Ember");

        //Upgrades
        add(JDTRegistration.TEMPLATE_FERRICORE.get(), "Template: Ferricore");
        add(JDTRegistration.TEMPLATE_BLAZEGOLD.get(), "Template: Blazegold");
        add(JDTRegistration.TEMPLATE_CELESTIGEM.get(), "Template: Celestigem");
        add(JDTRegistration.TEMPLATE_ECLIPSEALLOY.get(), "Template: Eclipse Alloy");
        add(JDTRegistration.UPGRADE_BASE.get(), "Upgrade: Blank");
        add(JDTRegistration.UPGRADE_MOBSCANNER.get(), "Upgrade: Mob Scanner");
        add(JDTRegistration.UPGRADE_OREMINER.get(), "Upgrade: Ore Miner");
        add(JDTRegistration.UPGRADE_ORESCANNER.get(), "Upgrade: Ore Scanner");
        add(JDTRegistration.UPGRADE_LAWNMOWER.get(), "Upgrade: Lawnmower");
        add(JDTRegistration.UPGRADE_SKYSWEEPER.get(), "Upgrade: Skysweeper");
        add(JDTRegistration.UPGRADE_TREEFELLER.get(), "Upgrade: Treefeller");
        add(JDTRegistration.UPGRADE_LEAFBREAKER.get(), "Upgrade: Leafbreaker");
        add(JDTRegistration.UPGRADE_RUNSPEED.get(), "Upgrade: Run Speed");
        add(JDTRegistration.UPGRADE_WALKSPEED.get(), "Upgrade: Walk Speed");
        add(JDTRegistration.UPGRADE_STEPHEIGHT.get(), "Upgrade: Step Assist");
        add(JDTRegistration.UPGRADE_JUMPBOOST.get(), "Upgrade: Jump Boost");
        add(JDTRegistration.UPGRADE_MINDFOG.get(), "Upgrade: Mind Fog");
        add(JDTRegistration.UPGRADE_INVULNERABILITY.get(), "Upgrade: Invulnerability");
        add(JDTRegistration.UPGRADE_SMELTER.get(), "Upgrade: Smelter");
        add(JDTRegistration.UPGRADE_SMOKER.get(), "Upgrade: Smoker");
        add(JDTRegistration.UPGRADE_HAMMER.get(), "Upgrade: Hammer");
        add(JDTRegistration.UPGRADE_CAUTERIZEWOUNDS.get(), "Upgrade: Cauterize Wounds");
        add(JDTRegistration.UPGRADE_SWIMSPEED.get(), "Upgrade: Swim Speed");
        add(JDTRegistration.UPGRADE_GROUNDSTOMP.get(), "Upgrade: Ground Stomp");
        add(JDTRegistration.UPGRADE_EXTINGUISH.get(), "Upgrade: Extinguish");
        add(JDTRegistration.UPGRADE_STUPEFY.get(), "Upgrade: Stupefy");
        add(JDTRegistration.UPGRADE_DROPTELEPORT.get(), "Upgrade: Drops Teleport");
        add(JDTRegistration.UPGRADE_NEGATEFALLDAMAGE.get(), "Upgrade: Negate Fall Damage");
        add(JDTRegistration.UPGRADE_NIGHTVISION.get(), "Upgrade: Night Vision");
        add(JDTRegistration.UPGRADE_DECOY.get(), "Upgrade: Decoy");
        add(JDTRegistration.UPGRADE_ELYTRA.get(), "Upgrade: Elytra");
        add(JDTRegistration.UPGRADE_DEBUFFREMOVER.get(), "Upgrade: Debuff Remover");
        add(JDTRegistration.UPGRADE_DEATHPROTECTION.get(), "Upgrade: Death Protection");
        add(JDTRegistration.UPGRADE_OREXRAY.get(), "Upgrade: Ore X-Ray");
        add(JDTRegistration.UPGRADE_GLOWING.get(), "Upgrade: Mob X-Ray");
        add(JDTRegistration.UPGRADE_INSTABREAK.get(), "Upgrade: Instant Break");
        add(JDTRegistration.UPGRADE_EARTHQUAKE.get(), "Upgrade: Earthquake");
        add(JDTRegistration.UPGRADE_NOAI.get(), "Upgrade: Mental Obliteration");
        add(JDTRegistration.UPGRADE_FLIGHT.get(), "Upgrade: Flight");
        add(JDTRegistration.UPGRADE_LAVAIMMUNITY.get(), "Upgrade: Lava Immunity");
        add(JDTRegistration.UPGRADE_PHASE.get(), "Upgrade: Phase");
        add(JDTRegistration.UPGRADE_SPLASH.get(), "Upgrade: Splash");
        add(JDTRegistration.UPGRADE_LINGERING.get(), "Upgrade: Lingering");
        add(JDTRegistration.UPGRADE_POTIONARROW.get(), "Upgrade: Potion Arrow");
        add(JDTRegistration.UPGRADE_HOMING.get(), "Upgrade: Homing Arrow");
        add(JDTRegistration.UPGRADE_EPICARROW.get(), "Upgrade: Yondu Arrow");
        add(JDTRegistration.UPGRADE_TIMEPROTECTION.get(), "Upgrade: Time Protection");
        add(JDTRegistration.UPGRADE_WATERBREATHING.get(), "Upgrade: Water Breathing");

        //Upgrade Text
        add("justdirethings." + Ability.MOBSCANNER.getName() + ".detailtext", "Show the location of nearby mobs");
        add("justdirethings." + Ability.MOBSCANNER.getName() + ".flavortext", "Whats making THAT noise?!");
        add("justdirethings." + Ability.OREMINER.getName() + ".detailtext", "Auto Harvest connected ores");
        //add("justdirethings." + Ability.OREMINER.getName() + ".flavortext", "Whats making THAT noise?!");
        add("justdirethings." + Ability.ORESCANNER.getName() + ".detailtext", "Show the location of nearby ores");
        //add("justdirethings." + Ability.ORESCANNER.getName() + ".flavortext", "Whats making THAT noise?!");
        add("justdirethings." + Ability.LAWNMOWER.getName() + ".detailtext", "Harvest all nearby grass");
        //add("justdirethings." + Ability.LAWNMOWER.getName() + ".flavortext", "Whats making THAT noise?!");
        add("justdirethings." + Ability.SKYSWEEPER.getName() + ".detailtext", "Clear falling blocks above the one you break");
        add("justdirethings." + Ability.SKYSWEEPER.getName() + ".flavortext", "Oww my head!");
        add("justdirethings." + Ability.TREEFELLER.getName() + ".detailtext", "Chop down trees in 1 fell swoop");
        //add("justdirethings." + Ability.TREEFELLER.getName() + ".flavortext", "Whats making THAT noise?!");
        add("justdirethings." + Ability.LEAFBREAKER.getName() + ".detailtext", "Clear nearby leaves");
        add("justdirethings." + Ability.LEAFBREAKER.getName() + ".flavortext", "Seriously, who doesn't have fast leaf decay");
        add("justdirethings." + Ability.RUNSPEED.getName() + ".detailtext", "Run Faster");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.WALKSPEED.getName() + ".detailtext", "Walk Faster");
        //add("justdirethings." + Ability.WALKSPEED.getName() + ".flavortext", "Whats making THAT noise?!");
        add("justdirethings." + Ability.STEPHEIGHT.getName() + ".detailtext", "Automatically step up 1 block");
        //add("justdirethings." + Ability.STEPHEIGHT.getName() + ".flavortext", "");
        add("justdirethings." + Ability.JUMPBOOST.getName() + ".detailtext", "Jump Higher");
        //add("justdirethings." + Ability.JUMPBOOST.getName() + ".flavortext", "Whats making THAT noise?!");
        add("justdirethings." + Ability.MINDFOG.getName() + ".detailtext", "Mobs are less likely to notice you");
        //add("justdirethings." + Ability.MINDFOG.getName() + ".flavortext", "Be vewy vewy quiet!");
        add("justdirethings." + Ability.INVULNERABILITY.getName() + ".detailtext", "Activate for a few seconds of invulnerability");
        add("justdirethings." + Ability.INVULNERABILITY.getName() + ".flavortext", "Bring it!!");
        add("justdirethings." + Ability.POTIONARROW.getName() + ".detailtext", "Insert a Potion Canister to apply effects to enemies");
        add("justdirethings." + Ability.POTIONARROW.getName() + ".flavortext", "Like Vanilla, without inventory issues...");
        add("justdirethings." + Ability.SMELTER.getName() + ".detailtext", "Auto Smelt Block Drops");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.SMOKER.getName() + ".detailtext", "Auto Smelt Mob Drops");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.HAMMER.getName() + ".detailtext", "3x3, 5x5, or 7x7 depending on tool tier");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.LAVAREPAIR.getName() + ".detailtext", "Drop item in Lava to repair it");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.CAUTERIZEWOUNDS.getName() + ".detailtext", "Activate to heal yourself");
        add("justdirethings." + Ability.CAUTERIZEWOUNDS.getName() + ".flavortext", "Feel the Burn!");
        add("justdirethings." + Ability.AIRBURST.getName() + ".detailtext", "Launch yourself in the direction you're looking");
        add("justdirethings." + Ability.AIRBURST.getName() + ".flavortext", "Safer than Fireworks");
        add("justdirethings." + Ability.SWIMSPEED.getName() + ".detailtext", "Swim Faster");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.GROUNDSTOMP.getName() + ".detailtext", "Activate to push mobs away");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.EXTINGUISH.getName() + ".detailtext", "Removes Burning Effect");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.STUPEFY.getName() + ".detailtext", "Activate to make the targeted mob forget you");
        add("justdirethings." + Ability.STUPEFY.getName() + ".flavortext", "Professor Lockhart would be proud");
        add("justdirethings." + Ability.SPLASH.getName() + ".detailtext", "Add splash effect to your potions");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.DROPTELEPORT.getName() + ".detailtext", "Bind tool to chest, and drops will teleport there");
        add("justdirethings." + Ability.DROPTELEPORT.getName() + ".flavortext", "My inventory is a mess -Dire Probably");
        add("justdirethings." + Ability.VOIDSHIFT.getName() + ".detailtext", "Teleport to where you're looking");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.NEGATEFALLDAMAGE.getName() + ".detailtext", "No fall damage");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.NIGHTVISION.getName() + ".detailtext", "Automatic Night Vision");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.ELYTRA.getName() + ".detailtext", "Built In Elytra");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.DECOY.getName() + ".detailtext", "Activate to summon a decoy that mobs will attack");
        //add("justdirethings." + Ability.DECOY.getName() + ".flavortext", "");
        add("justdirethings." + Ability.LINGERING.getName() + ".detailtext", "Lingering effect on potions");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.HOMING.getName() + ".detailtext", "Arrows seek their targets");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.OREXRAY.getName() + ".detailtext", "See all nearby ores");
        add("justdirethings." + Ability.OREXRAY.getName() + ".flavortext", "Thats Overpowered!!");
        add("justdirethings." + Ability.GLOWING.getName() + ".detailtext", "See all nearby mobs");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.INSTABREAK.getName() + ".detailtext", "Instantly break all blocks");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.ECLIPSEGATE.getName() + ".detailtext", "Temporarily remove blocks you click on");
        add("justdirethings." + Ability.ECLIPSEGATE.getName() + ".flavortext", "I just missed the portable hole, ok?");
        add("justdirethings." + Ability.DEATHPROTECTION.getName() + ".detailtext", "Prevents death once every 5 minutes");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.DEBUFFREMOVER.getName() + ".detailtext", "Activate to Remove negative effects");
        add("justdirethings." + Ability.DEBUFFREMOVER.getName() + ".flavortext", "Milk not included");
        add("justdirethings." + Ability.EARTHQUAKE.getName() + ".detailtext", "Slow all nearby mobs");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.NOAI.getName() + ".detailtext", "Nearby mobs completely stop. Forever.");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.FLIGHT.getName() + ".detailtext", "Creative mode style flight");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.LAVAIMMUNITY.getName() + ".detailtext", "No Damage from Lava or Fire");
        add("justdirethings." + Ability.LAVAIMMUNITY.getName() + ".flavortext", "Fancy a swim?");
        add("justdirethings." + Ability.PHASE.getName() + ".detailtext", "Walk through walls");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.EPICARROW.getName() + ".detailtext", "Arrows can hit multiple targets");
        add("justdirethings." + Ability.EPICARROW.getName() + ".flavortext", "I'm Mary Poppins Ya'll");
        add("justdirethings." + Ability.TIMEPROTECTION.getName() + ".detailtext", "Protection from Time Altering Effects");
        //add("justdirethings." + Ability.RUNSPEED.getName() + ".flavortext", "");
        add("justdirethings." + Ability.WATERBREATHING.getName() + ".detailtext", "Allows player to breath under water");
        add("justdirethings." + Ability.WATERBREATHING.getName() + ".flavortext", "Just keep swimming, just keep swimming!");


        //Misc
        add("justdirethings.shiftmoreinfo", "Hold Shift for details");
        add("justdirethings.presshotkey", "<Press %s>");
        add("justdirethings.enabled", "Enabled");
        add("justdirethings.disabled", "Disabled");
        add("justdirethings.lowenergy", "Insufficient Energy");
        add("justdirethings.fuelcanisteramt", "Cook time (ticks): %d");
        add("justdirethings.fuelcanisteramtstack", "Stack Cook time (ticks): %d");
        add("justdirethings.fuelcanisteritemsamt", "Fuel Amount: %f");
        add("justdirethings.fuelcanisteritemsamtstack", "Stack Fuel Amount: %f");
        add("justdirethings.pocketgeneratorburntime", "Burn Time: %f / %f");
        add("justdirethings.pocketgeneratorfuelstack", "Fuel: %f %s");
        add("justdirethings.pocketgeneratornofuel", "Fuel Empty");
        add("justdirethings.festored", "Forge Energy: %s / %s");
        add("justdirethings.portalfluidamt", "Portal Fluid: %s / %s");
        add("justdirethings.timefluidamt", "Time Fluid: %s / %s");
        add("justdirethings.polymorphicfluidamt", "Polymorphic Fluid: %s / %s");
        add("justdirethings.paradoxenergy", "Paradox Energy: %s / %s");
        add("justdirethings.lowportalfluid", "Insufficient Portal Fluid");
        add("justdirethings.lowtimefluid", "Insufficient Time Fluid");
        add("justdirethings.invalidpolymorphentity", "Invalid Entity for Polymorphing");
        add("justdirethings.polymorphset", "Polymorph Target: %s");
        add("justdirethings.boundto", "Bound to: %s:%s");
        add("justdirethings.boundto-missing", "Bound to (MISSING BLOCK): %s:%s");
        add("justdirethings.unbound", " -Not Bound");
        add("justdirethings.bindfailed", "Binding Failed");
        add("justdirethings.bindremoved", "Binding Removed");
        add("justdirethings.unbound-screen", "Not Bound");
        add("justdirethings.bound-key", "Bound to: %s");
        add("justdirethings.bound-mouse", "Mouse Button: %s");
        add("justdirethings.boundside", " -Bound Side: ");
        add("justdirethings.creature", "Creature: ");
        add("justdirethings.ability", "Ability: %s - %s");
        add("justdirethings.toolenabled", "Tool: %s - %s");
        add("justdirethings.settingscopied", "Settings Copied");
        add("justdirethings.settingspasted", "Settings Pasted");
        add("justdirethings.fillmode.changed", "Fill Mode Set to: %s");
        add("justdirethings.fluidamt", "Amount: ");
        add("justdirethings.fluidname", "Fluid: ");
        add("justdirethings.fillmode", "Fill Mode: ");
        add("justdirethings.fillmode.none", "None");
        add("justdirethings.fillmode.jdtonly", "JustDireThings");
        add("justdirethings.fillmode.all", "All");
        add("justdirethings.hint.dropinwater", "Drop in Water");
        add("justdirethings.decoy", "Decoy");
        add("justdirethings.missingupgrade", " (Missing Upgrade)");
        add("justdirethings.requiresfeeding", "Click on the block with its food to activate it");
        add("justdirethings.timecrystaltooltip", "Wibbly Wobbly");
        add("justdirethings.timecrystaltooltiptwo", "Timey Wimey");

        //Keys
        add("key.category.justdirethings.category", "Just Dire Things");
        add("justdirethings.key.toggle_tool", "Toggle Tool Abilities");
        add("justdirethings.key.toolUI", "Open Tool Settings UI");

        //Abilities
        add(Ability.MOBSCANNER.getLocalization(), "Mob Scanner");
        add(Ability.ORESCANNER.getLocalization(), "Ore Scanner");
        add(Ability.OREMINER.getLocalization(), "Ore Miner");
        add(Ability.LAWNMOWER.getLocalization(), "Lawnmower");
        add(Ability.SKYSWEEPER.getLocalization(), "Sky Sweeper");
        add(Ability.TREEFELLER.getLocalization(), "Tree Feller");
        add(Ability.LEAFBREAKER.getLocalization(), "Leaf Breaker");
        add(Ability.SMELTER.getLocalization(), "Auto Smelter");
        add(Ability.SMOKER.getLocalization(), "Auto Smoker");
        add(Ability.LAVAREPAIR.getLocalization(), "Lava Repair");
        add(Ability.CAUTERIZEWOUNDS.getLocalization(), "Cauterize Wounds");
        add(Ability.HAMMER.getLocalization(), "Hammer");
        add(Ability.HAMMER.getLocalization() + "_off", "Hammer: Disabled");
        add(Ability.HAMMER.getLocalization() + "_3", "Hammer: 3x3");
        add(Ability.HAMMER.getLocalization() + "_5", "Hammer: 5x5");
        add(Ability.HAMMER.getLocalization() + "_7", "Hammer: 7x7");
        add(Ability.OREXRAY.getLocalization(), "X-Ray");
        add(Ability.DROPTELEPORT.getLocalization(), "Drops Teleporter");
        add(Ability.GLOWING.getLocalization(), "Mob X-Ray");
        add(Ability.INSTABREAK.getLocalization(), "Instant Break");
        add(Ability.AIRBURST.getLocalization(), "Air Burst");
        add(Ability.VOIDSHIFT.getLocalization(), "Void Shift");
        add(Ability.ECLIPSEGATE.getLocalization(), "Eclipse Gate");
        add(Ability.RUNSPEED.getLocalization(), "Run Speed");
        add(Ability.WALKSPEED.getLocalization(), "Walk Speed");
        add(Ability.SWIMSPEED.getLocalization(), "Swim Speed");
        add(Ability.GROUNDSTOMP.getLocalization(), "Ground Stomp");
        add(Ability.EXTINGUISH.getLocalization(), "Extinguish");
        add(Ability.STUPEFY.getLocalization(), "Stupefy");
        add(Ability.STEPHEIGHT.getLocalization(), "Step Assist");
        add(Ability.JUMPBOOST.getLocalization(), "Jump Boost");
        add(Ability.MINDFOG.getLocalization(), "Mind Fog");
        add(Ability.INVULNERABILITY.getLocalization(), "Invulnerability");
        add(Ability.ELYTRA.getLocalization(), "Elytra");
        add(Ability.NEGATEFALLDAMAGE.getLocalization(), "Negate Fall Damage");
        add(Ability.DECOY.getLocalization(), "Decoy");
        add(Ability.NIGHTVISION.getLocalization(), "Night Vision");
        add(Ability.DEATHPROTECTION.getLocalization(), "Death Protection");
        add(Ability.DEBUFFREMOVER.getLocalization(), "Debuff Remover");
        add(Ability.NOAI.getLocalization(), "Mental Obliteration");
        add(Ability.FLIGHT.getLocalization(), "Flight");
        add(Ability.LAVAIMMUNITY.getLocalization(), "Lava Immunity");
        add(Ability.PHASE.getLocalization(), "Phase");
        add(Ability.EARTHQUAKE.getLocalization(), "Earthquake");
        add(Ability.SPLASH.getLocalization(), "Splash");
        add(Ability.LINGERING.getLocalization(), "Lingering");
        add(Ability.POTIONARROW.getLocalization(), "Potion Arrow");
        add(Ability.HOMING.getLocalization(), "Homing Arrow");
        add(Ability.EPICARROW.getLocalization(), "Yondu Arrow");
        add(Ability.TIMEPROTECTION.getLocalization(), "Time Protection");
        add(Ability.WATERBREATHING.getLocalization(), "Water Breathing");
        add(Ability.POLYMORPH_RANDOM.getLocalization(), "Random Polymorph");
        add(Ability.POLYMORPH_TARGET.getLocalization(), "Targeted Polymorph");

        //GUI
        add("justdirethings.screen.energy", "Energy: %s/%s FE");
        add("justdirethings.screen.fluid", "%s: %s/%s MB");
        add("justdirethings.screen.energycost", "Energy Cost: %s");
        add("justdirethings.screen.fepertick", "FE/T: %s");
        add("justdirethings.screen.no_fuel", "Fuel source empty");
        add("justdirethings.screen.burn_time", "Burn time left: %ss");
        add("justdirethings.screen.ignored", "Ignored");
        add("justdirethings.screen.low", "Low");
        add("justdirethings.screen.high", "High");
        add("justdirethings.screen.pulse", "Pulse");
        add("justdirethings.screen.allowlist", "Allow List");
        add("justdirethings.screen.denylist", "Deny List");
        add("justdirethings.screen.filteronlytrue", "Filtered Items Only");
        add("justdirethings.screen.renderarea", "Render Area");
        add("justdirethings.screen.comparenbt", "Compare NBT");
        add("justdirethings.screen.comparecounts", "Compare Stack Sizes");
        add("justdirethings.screen.direction-down", "Down");
        add("justdirethings.screen.direction-up", "Up");
        add("justdirethings.screen.direction-north", "North");
        add("justdirethings.screen.direction-south", "South");
        add("justdirethings.screen.direction-west", "West");
        add("justdirethings.screen.direction-east", "East");
        add("justdirethings.screen.direction-none", "None");
        add("justdirethings.screen.filter-block", "Filter: Block");
        add("justdirethings.screen.filter-item", "Filter: Item");
        add("justdirethings.screen.tickspeed", "Speed (Ticks)");
        add("justdirethings.screen.pickupdelay", "Pickup Delay (Ticks)");
        add("justdirethings.screen.click-right", "Right Click");
        add("justdirethings.screen.click-left", "Left Click");
        add("justdirethings.screen.click-custom", "Custom Binding");
        add("justdirethings.screen.setbinding", "Set Binding");
        add("justdirethings.screen.target-block", "Target Blocks");
        add("justdirethings.screen.target-noblock", "Ignore Blocks");
        add("justdirethings.screen.target-air", "Target Air");
        add("justdirethings.screen.target-hostile", "Target Hostile");
        add("justdirethings.screen.target-passive", "Target Passive");
        add("justdirethings.screen.target-adult", "Target Adult");
        add("justdirethings.screen.target-child", "Target Child");
        add("justdirethings.screen.target-player", "Target Player");
        add("justdirethings.screen.target-living", "Target All Living");
        add("justdirethings.screen.target-item", "Target Items");
        add("justdirethings.screen.entity-none", "No Entities");
        add("justdirethings.screen.entity-all", "All Entities");
        add("justdirethings.screen.sneak-click", "Sneak Click");
        add("justdirethings.screen.showfakeplayer", "Show Fake Player");
        add("justdirethings.screen.redstone-weak", "Weak Signal");
        add("justdirethings.screen.redstone-strong", "Strong Signal");
        add("justdirethings.screen.senseamount", "Sense Amount");
        add("justdirethings.screen.greaterthan", "Greater Than");
        add("justdirethings.screen.lessthan", "Less Than");
        add("justdirethings.screen.equals", "Equals");
        add("justdirethings.screen.dropcount", "Drop Amount");
        add("justdirethings.screen.showparticles", "Show Particles");
        add("justdirethings.screen.showrender", "Show Render");
        add("justdirethings.screen.hiderender", "Hide Render");
        add("justdirethings.screen.burnspeedmultiplier", "Burn Speed Multiplier: %s");
        add("justdirethings.screen.click-hold", "Hold Click");
        add("justdirethings.screen.requireequipped", "Activate if Equipped");
        add("justdirethings.screen.notrequireequipped", "Activate from Inventory");
        add("justdirethings.screen.click-hold-for", "Hold Click For (ticks)");
        add("justdirethings.screen.inv-normal", "Full Inventory");
        add("justdirethings.screen.inv-armor", "Armor Slots");
        add("justdirethings.screen.inv-offhand", "Offhand Slots");
        add("justdirethings.screen.inv-main", "Main Inventory");
        add("justdirethings.screen.inv-hotbar", "Hotbar Only");
        add("justdirethings.screen.rightclicksettings", "Right Click for Settings");
        add("justdirethings.screen.copy_area", "Copy Area");
        add("justdirethings.screen.copy_offset", "Copy Offset");
        add("justdirethings.screen.copy_filter", "Copy Filters");
        add("justdirethings.screen.copy_redstone", "Copy Redstone");
        add("justdirethings.screen.add_favorite", "Add Favorite");
        add("justdirethings.screen.remove_favorite", "Remove Favorite");
        add("justdirethings.screen.edit_favorite", "Edit Favorite");
        add("justdirethings.screen.stay_open", "Stay Open");
        add("justdirethings.screen.save_close", "Save and Close");
        add("justdirethings.screen.cancel", "Cancel");
        add("justdirethings.screen.snapshotarea", "Snapshot Area");
        add("justdirethings.screen.renderparadox", "Render Paradox");
        add("justdirethings.screen.paradoxentity", "Revert Entities");
        add("justdirethings.screen.paradoxblock", "Revert Blocks");
        add("justdirethings.screen.paradoxall", "Revert Blocks and Entities");
        add("justdirethings.screen.paradoxenergycost", "Energy Cost: %s FE");
        add("justdirethings.screen.paradoxfluidcost", "Fluid Cost: %s mb");
        add("justdirethings.screen.senditems", "Push Items");
        add("justdirethings.screen.pullitems", "Pull Items");
        add("justdirethings.screen.swapitems", "Swap Items");
        add("justdirethings.screen.storeexp", "Store Level");
        add("justdirethings.screen.retrieveexp", "Retrieve Level");
        add("justdirethings.screen.targetexp", "Target Level");
        add("justdirethings.screen.owneronly", "Owner Only");
        add("justdirethings.screen.collectexp", "Collect Experience");
        add("justdirethings.screen.pushfluids", "Push Fluids");
        add("justdirethings.screen.pullfluids", "Pull Fluids");
        add("justdirethings.screen.respectpickupdelay", "Respect Item Pickup Delay");

        //Buttons
        //add("justdirethings.buttons.save", "Save");

        //Entities
        add("entity.justdirethings.decoy_entity", "Decoy Entity");
        add("entity.justdirethings.time_wand_entity", "Time Wand Entity");
        add("entity.justdirethings.paradox_entity", "Paradox");
        add("entity.justdirethings.portal_entity", "DirePortal");
        add("entity.justdirethings.portal_projectile", "Portal Projectile");
        add("entity.justdirethings.creature_catcher", "Creature Catcher");
        add("entity.justdirethings.justdirearrow", "Dire Arrow");
        add("entity.justdirethings.justdireareaeffectcloud", "Area Effect Cloud");

        //Recipes
        add("justdirethings.goospreadrecipe.title", "Goo Spreading Recipes");
        add("justdirethings.goospreadrecipetag.title", "Tagged Goo Spreading Recipes");
        add("justdirethings.oretoresource.title", "Ores to Resources");
        add("justdirethings.fluiddroprecipe.title", "Fluid Drop Recipes");

        //Sounds
        add("sound.justdirethings.beep", "Beep");
        add("sound.justdirethings.portal_gun_close", "Portal Gun Close");
        add("sound.justdirethings.portal_gun_open", "Portal Gun Open");
        add("sound.justdirethings.paradox_ambient", "Paradox Machine Ambient");
    }
}
